version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "automate-me"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1js8c43fg5qf1"
s3_prefix = "automate-me"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
